# Generated by Django 4.2.3 on 2023-07-30 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='is_favourite',
            new_name='is_favorite',
        ),
    ]
